# Blaze Worlds Texas Championship Edition - Netlify Configuration

[build]
  publish = "dist/"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=UTF-8"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/javascript; charset=UTF-8"

[[redirects]]
  from = "/"
  to = "/blaze-worlds-launcher.html"
  status = 200

[[redirects]]
  from = "/championship"
  to = "/blaze-worlds-texas-championship.html"
  status = 200

[[redirects]]
  from = "/data-stories"
  to = "/data-stories/championship-case-studies.html"
  status = 200

[[redirects]]
  from = "/stories"
  to = "/data-stories/championship-case-studies.html"
  status = 200

[[redirects]]
  from = "/texas"
  to = "/blaze-worlds-texas-championship.html"
  status = 301

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

  [plugins.inputs]
    extract = true
    dimensions = [
      { width = 414, height = 896 },
      { width = 1920, height = 1080 }
    ]